<a href="https://colab.research.google.com/github/ramirezcarlos292/miaad_python_programming/blob/main/practices/Practica_19_Datos_duplicados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practica 19 Datos Duplicados



---



Alumno: Carlos Iván Ramírez Martínez <br>
Matricula: 260499 <br>
Email: al260499@alumnos.uacj.mx <br>


---



## Objetivo:
El objetivo de esta actividad es que los estudiantes pongan en práctica lo visto en el vídeo y en el notebook que se proporciona.

## Instrucciones:

- Descarga el archivo dirtydata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
- Crea un notebook en colab y guarda el archivo csv  en tu drive.
- Agrega secciones en el colab poniendo como título el nombre de cada ejercicio.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

!wget -P /content/drive/MyDrive/ClassFiles/ https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/dirtydata.csv

--2025-09-26 00:32:41--  https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/dirtydata.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 965 [text/plain]
Saving to: ‘/content/drive/MyDrive/ClassFiles/dirtydata.csv.19’

dirtydata.csv.19    100%[===================>]     965  --.-KB/s    in 0s

2025-09-26 00:32:41 (23.5 MB/s) - ‘/content/drive/MyDrive/ClassFiles/dirtydata.csv.19’ saved [965/965]

### Ejercicio 01
Duplicidad Parcial Una columna: Contar y Filtrar los registros duplicados en Duration

**1.1** Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta. <br>
**1.2** Cuenta la cantidad de registros duplicados utilizando solo la información de columna Duration e imprime.<br>
**1.3** Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.<br>
**1.4** Filtra los datos y obten los registros sin duplicados.<br>

In [ ]:
print(f"1.1 Carga el conjunto de datos:")
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/dirtydata.csv')
df.head(5)

1.1 Carga el conjunto de datos:

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
print(f"1.2 Cuantos datos duplicados existen en la columna 'Duration'?")
print(f"    En la columna 'Duration' existen: {int(df.duplicated(subset=['Duration']).sum())} datos duplicados")

1.2 Cuantos datos duplicados existen en la columna 'Duration'?
    En la columna 'Duration' existen: 28 datos duplicados

In [ ]:
print(f"1.3 Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.")
print(f"    Cuenta de valores únicos en la columna Duration")
df['Duration'].value_counts()

1.3 Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.
    Cuenta de valores únicos en la columna Duration

Duration
60     24
45      6
450     1
30      1
Name: count, dtype: int64

In [ ]:
print(f"1.4 Filtra los datos y obten los registros sin duplicados.")
df.drop_duplicates(subset=['Duration'], keep=False, inplace=True)
print(len(df))
df

1.4 Filtra los datos y obten los registros sin duplicados.
2

   Duration          Date  Pulse  Maxpulse  Calories
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1

### Ejercicio 02
Duplicidad Parcial Dos columna: Contar y Filtrar los registros duplicados en Pulse y MaxPulse

**2.1** Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.<br>
**2.2** Cuenta la cantidad de registros duplicados utilizando la información de las columnas Pulse y Maxpulse.<br>
**2.3** Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.<br>
**2.4** Filtra los datos y obten los registros cuando keep = 'last'.<br>

In [ ]:
print(f"2.1 Carga el conjunto de datos:")
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/dirtydata.csv')
df_original_len = len(df)
print(f"Cantidad de rows del dataset original {df_original_len}")
df.head(5)

2.1 Carga el conjunto de datos:
Cantidad de rows del dataset original 32

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
print(f"2.2 Cuantos datos duplicados existen en la columna 'Pulse' y 'Maxpulse'?")
print(f"    En las columns 'Pulse' existen: {int(df.duplicated(subset=['Pulse'], keep=False).sum())} datos duplicados")
print(f"    En las columns 'Maxpulse' existen: {int(df.duplicated(subset=['Maxpulse'], keep=False).sum())} datos duplicados")

2.2 Cuantos datos duplicados existen en la columna 'Pulse' y 'Maxpulse'?
    En las columns 'Pulse' existen: 26 datos duplicados
    En las columns 'Maxpulse' existen: 11 datos duplicados

In [ ]:
print(f"2.3 Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.\n")
print(f"----Cuenta de valores únicos en la columna 'Pulse': \n{df['Pulse'].value_counts()}\n")
print(f"----Cuenta de valores únicos en la columna 'Maxpulse':\n{df['Maxpulse'].value_counts()}\n")

2.3 Utiliza value_counts() e imprime la cantidad de registros que hay por cada valor único.

----Cuenta de valores únicos en la columna 'Pulse':
Pulse
100    6
103    4
98     3
102    3
117    2
109    2
110    2
104    2
92     2
90     1
106    1
97     1
108    1
130    1
105    1
Name: count, dtype: int64

----Cuenta de valores únicos en la columna 'Maxpulse':
Maxpulse
120    5
132    4
123    2
130    1
148    1
145    1
135    1
175    1
134    1
136    1
127    1
133    1
147    1
124    1
128    1
112    1
125    1
131    1
119    1
101    1
126    1
118    1
129    1
115    1
Name: count, dtype: int64

In [ ]:
print(f"2.4 Filtra los datos y obten los registros cuando keep = 'last'.")
df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last', inplace=True)
print(f"Después de remover duplicados de columnas, 'Pulse' y 'Maxpulse', quedaron y conservar 'last': {len(df)}")
df

2.4 Filtra los datos y obten los registros cuando keep = 'last'.
Después de remover duplicados de columnas, 'Pulse' y 'Maxpulse', quedaron y conservar 'last': 29

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

### Ejercicio 03
Duplicidad Total o Exacta: Contar y Filtrar los registros duplicados

**3.1** Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.<br>
**3.2** Cuenta la cantidad de registros duplicados exactos (todas las columnas).<br>
**3.3** Utiliza sum() e imprime la cantidad de registros con duplicidad exacta.<br>
**3.4** Filtra los datos y obten los registros cuando keep = 'last'.<br>

In [ ]:
print(f"3.1 Carga el conjunto de datos:")
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/dirtydata.csv')
df_original_len = len(df)
df.head()

3.1 Carga el conjunto de datos:

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
print(f"3.2 Cuantos datos duplicados existen en el conjunto de datos?")
print(f"    En las columnas del conjunto de datos existen {int(df.duplicated(keep=False).sum())} registros con duplicidad exacta")

3.2 Cuantos datos duplicados existen en el conjunto de datos?
    En las columnas del conjunto de datos existen 2 registros con duplicidad exacta

In [ ]:
print(f"3.3 Utiliza sum() e imprime la cantidad de registros con duplicidad exacta.")
df[df.duplicated(keep=False)]

3.3 Utiliza sum() e imprime la cantidad de registros con duplicidad exacta.

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7

In [ ]:
print(f"3.4 Filtra los datos y obten los registros cuando keep = 'last'.")
print(f"Número de renglones antes de remover duplicados: {len(df)}")

df.drop_duplicates(keep='last', inplace=True)
print(f"Número de renglones después de remover duplicados: {len(df)}")
df

3.4 Filtra los datos y obten los registros cuando keep = 'last'.
Número de renglones antes de remover duplicados: 32
Número de renglones después de remover duplicados: 31

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

### Ejercicio 04: Cálculo de la media con duplicados y sin duplicados

**4.1** Carga el conjunto de datos dirty.csv y verifica que su carga sea correcta.<br>
**4.2** Calcula e imprime la media de las columnas Pulse y MaxPulse.<br>
**4.3** Identifica los valores duplicados en las columnas Pulse y MaxPulse.<br>(Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias.<br>
**4.4** Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse.<br>

In [ ]:
print(f"4.1 Carga el conjunto de datos:")
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/dirtydata.csv')
df_original_len = len(df)
df.head()

4.1 Carga el conjunto de datos:

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
print(f"4.2 Calcula e imprime la media de las columnas Pulse y MaxPulse.")
print(f"Media {df['Pulse'].mean()}")
print(f"Media {df['Maxpulse'].mean()}")

4.2 Calcula e imprime la media de las columnas Pulse y MaxPulse.
Media 103.5
Media 128.5

In [ ]:
print(f'''4.3 Identifica los valores duplicados en las columnas Pulse y MaxPulse.
(Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias.''')

df[df.duplicated(subset=['Pulse', 'Maxpulse'], keep=False)]

4.3 Identifica los valores duplicados en las columnas Pulse y MaxPulse.
(Duplicidad Parcial) y elimina los registro repetidos. Quédate con las últimas ocurrencias.

    Duration          Date  Pulse  Maxpulse  Calories
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
17        60  '2020/12/17'    100       120     300.0
26        60      20201226    100       120     250.0

In [ ]:
df.drop_duplicates(subset=['Pulse', 'Maxpulse'], keep='last', inplace=True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
print(f'''4.4 Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron
las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse..''')
print(f"Media {df['Pulse'].mean()}")
print(f"Media {df['Maxpulse'].mean()}")

4.4 Utiliza el conjunto anterior sin datos duplicados (recuerda que solo quedaron
las últimas ocurrencias de los datos) y calcula la media de las columnas Pulse y MaxPulse..
Media 103.86206896551724
Media 129.3793103448276