<a href="https://colab.research.google.com/github/ramirezcarlos292/miaad_python_programming/blob/main/practices/Pr%C3%A1ctica_18_Datos_Temporales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objetivo
El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

# Instrucciones:
* Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
* Crea un notebook en colab y guarda el archivo csv  en tu drive.
* Agrega secciones en el colab poniendo como título el nombre de cada ejercicio.

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

# Importar Librerías

In [2]:
import pandas as pd
import numpy as np
import datetime as dt

# Descargar conjunto de datos

In [3]:
!wget -P /content/drive/MyDrive/ClassFiles/ https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/Airdata.csv

--2025-09-14 03:53:14--  https://raw.githubusercontent.com/ramirezcarlos292/miaad_python_programming/refs/heads/main/datasets/Airdata.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 556033 (543K) [text/plain]
Saving to: ‘/content/drive/MyDrive/ClassFiles/Airdata.csv.2’

Airdata.csv.2       100%[===================>] 543.00K  --.-KB/s    in 0.07s

2025-09-14 03:53:14 (7.29 MB/s) - ‘/content/drive/MyDrive/ClassFiles/Airdata.csv.2’ saved [556033/556033]

In [4]:
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/Airdata.csv')
df.head()

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,1/1/2020 0:00,2.180529,87,1.484318,75.963760,39.23,52.88,62.37
1,1/1/2020 1:00,1.490529,89,2.741678,113.198590,38.30,44.95,52.53
2,1/1/2020 2:00,1.690529,85,3.563818,135.000000,NaN,48.40,54.80
3,1/1/2020 3:00,1.430529,84,2.811690,129.805570,37.28,47.18,50.80
4,1/1/2020 4:00,0.840529,86,1.800000,126.869896,29.97,41.48,54.43

# **Ejercicio 01:** Tipo de Datos Correcto

* Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto.
* Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.
* Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto.
* Imprime las primeras tres líneas.

In [5]:
# Parece que solo DateTime require conversión.
df.dtypes

DateTime           object
Temperature       float64
Humidity            int64
Wind_Speed        float64
Wind_Direction    float64
NO2_Location_A    float64
NO2_Location_B    float64
NO2_Location_C    float64
dtype: object

In [6]:
'''
Convertir:
  Datetime de object a datetime(ns)
'''
df['DateTime'] = pd.to_datetime(df['DateTime'])
print(f"Corrección de la columna 'DateTime':\n\n {df.dtypes}")
df.head(3)

Corrección de la columna 'DateTime':

 DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

# **Ejercicio 02:** Extraer componentes de fecha y tiempo

* De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes.
* Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

In [11]:
df['Year'] = df['DateTime'].dt.year
df['Month'] = df['DateTime'].dt.month
df['Day'] = df['DateTime'].dt.day
df['Hour'] = df['DateTime'].dt.hour
df = df[['DateTime', 'Year', 'Month', 'Day', 'Hour',
         'Temperature', 'Humidity', 'Wind_Speed', 'Wind_Direction',
         'NO2_Location_A', 'NO2_Location_B', 'NO2_Location_C']]
df.head(3)

,DateTime,Year,Month,Day,Hour,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2020,1,1,0,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,2020,1,1,1,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,2020,1,1,2,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

# **Ejercicio 03:** Aritmética - Suma de Intervalos (timedelta)

* Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'.
* Guarda el resultado en una nueva columna y agrega al dataframe.
* Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

In [8]:
df['DateTime_Offset'] = df['DateTime']+pd.Timedelta(days = 10, hours=7, minutes=15)
df[['DateTime', 'DateTime_Offset']]

                DateTime     DateTime_Offset
0    2020-01-01 00:00:00 2020-01-11 07:15:00
1    2020-01-01 01:00:00 2020-01-11 08:15:00
2    2020-01-01 02:00:00 2020-01-11 09:15:00
3    2020-01-01 03:00:00 2020-01-11 10:15:00
4    2020-01-01 04:00:00 2020-01-11 11:15:00
...                  ...                 ...
8779 2020-12-31 19:00:00 2021-01-11 02:15:00
8780 2020-12-31 20:00:00 2021-01-11 03:15:00
8781 2020-12-31 21:00:00 2021-01-11 04:15:00
8782 2020-12-31 22:00:00 2021-01-11 05:15:00
8783 2020-12-31 23:00:00 2021-01-11 06:15:00

[8784 rows x 2 columns]

# **Ejercicio 04:** Timestamp

* Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix.
* Guarda el resultado en una nueva columna
* Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix.

In [9]:
df['DateTime_ms'] = df['DateTime'].astype('int64') // 1_000_000
df['DateTime_Unix'] = pd.to_datetime(df['DateTime_ms'], unit='ms', origin='unix')

df[['DateTime', 'DateTime_Unix']].head(3)

             DateTime       DateTime_Unix
0 2020-01-01 00:00:00 2020-01-01 00:00:00
1 2020-01-01 01:00:00 2020-01-01 01:00:00
2 2020-01-01 02:00:00 2020-01-01 02:00:00

In [10]:
df[['DateTime', 'DateTime_Unix']].tail(3)

                DateTime       DateTime_Unix
8781 2020-12-31 21:00:00 2020-12-31 21:00:00
8782 2020-12-31 22:00:00 2020-12-31 22:00:00
8783 2020-12-31 23:00:00 2020-12-31 23:00:00